# Generated by Django 2.2.20 on 2021-12-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('audio', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='kitob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author_name', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='%Y%m%d')),
                ('file', models.FileField(blank=True, upload_to='')),
                ('categories', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='audio_kitob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author_name', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='%Y%m%d')),
                ('categories', models.CharField(default='audio_kitob', max_length=200)),
                ('content', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('audio', models.ManyToManyField(blank=True, null=True, to='myapp.audio')),
            ],
        ),
    ]
